### ISSUE TITLE
Transactions often "idle" for several blocks before being included

### ISSUE THREAD

**Issue by trendzetter** [kadena-io/chainweb-node#1613]
Some transactions are not included in the first block, it takes often several -near empty- blocks before a send transaction is actually mined by a node. I wonder if it could be partly because a large number of nodes are running the default -conservative- settings for the mempool resulting in slow propagation:
```
 pollInterval: 30
 maxSessionCount: 6
 sessionTimeout: 300
```
It's just speculation on my part but I hope it could improve propagation with defaults for mainnet set more like this:
```
 pollInterval: 10
 maxSessionCount: 30
 sessionTimeout: 150
```
Even tweaking the parameters on an individual node seems to improve request execution time but I hope having the majority of the nodes run more optimized parameters would result in a larger improvement because of network effects.

**Comment by trendzetter** [comment]
There is some research on the current situation: https://github.com/kadena-io/chainweb-node/issues/1622#issuecomment-1484248926

**Comment by jwiegley** [comment]
This is within expected range for our network. As with anything, latencies could very likely be improved if we made that more of an objective, but since we are already much faster (and cheaper) than other PoW L1 blockchains in operation, it makes more sense for us to spend our time in areas that provide higher impact.
