### ISSUE TITLE
Mempool Transaction Propagation

### ISSUE THREAD

**Issue by masch1na** [kadena-io/chainweb-node#1622]
Hello team,

Something is wrong with either of these or both.
a) How nodes propagate transactions from mempool to other nodes
b) How miners pick transactions to mine from mempool 

Problem description:
I send two transactions at the same time to the same node on the same chain with same parameters. Sometimes they are mined within the same block, but often they are mined 1-2-3 block heights between each other, often with the blocks inbetween just being empty. In a small test performed specifically for this github report, I sent 2 transactions at the same time 10 different times. Out of 10 times, 4 times one of the two transactions wasn't mined within the same block. Correct me if I'm wrong but this doesn't sound like it's working as intended.

Thank you.

**Comment by masch1na** [comment]
I think it's important to note that this test was performed against "chainweb.ecko.finance" node which is used by Ecko (Kaddex). The DEX has VERY little traffic for me to believe the delay is caused by any overload though. There were almost no swaps. This node is used by the go-to DEX (arguably), therefore these symptoms will be felt by majority of the Kadena ecosystem users, which is why I think it's worth investigating. 

Separate test against "api.chainweb.com" weilded the pretty much the same results. 

However, I was not able to replicate this issue when using my node or "kadena2.app.runonflux.io" which is used by KDSwap. 

Since I wasn't able to replicate this issue on my node or KDSwap node I wanted to close this report out, but I'll leave it open for any thoughts from the team.

**Comment by trendzetter** [comment]
It could be useful to compare actual config options set and different outcomes.

**Comment by trendzetter** [comment]
I didn't actually test the 2 transactions at the same time but here is related talk #1613

**Comment by masch1na** [comment]
Ah I wasn't aware there is a similar thread already open. If there is a way to merge them and if you think it's a good idea please feel free to do so.

With regards to comparing node configs and your suggestions in #1613 - my node is actually set up in similar way, those configs stood out to me as well.

I think it would be worth comparing configs, there used to be "https://api.chainweb.com/chainweb/{apiVersion}/mainnet01/config" endpoint as documented here https://api.chainweb.com/openapi/#tag/config/paths/~1config/get - but it doesn't seem to work anymore unfortunately. 

The only thing that makes me doubt these configurations are the cause of issues is because in my test, TXs were sent to the same node. It's very unlikely I didn't fit on so many ocassions into the "30 second" poll interval. 

But regardless, I wish the config endpoint would work.

**Comment by masch1na** [comment]
I would like to add that since the recent 2.18.1 (2023-03-06) chainweb change this problem seems to be worse than ever.

**Comment by wwared** [comment]
I believe that both `chainweb.ecko.finance` and `api.chainweb.com` are deployments using a load balancer in front of more than one node (so sending the same transaction to it twice can actually make it reach two different chainweb-node instances behind the load balancer), while the `kadena2.app.runonflux.io` deployment is a single chainweb-node instance hosted directly on Flux, so the config issues mentioned in #1613 might indeed be related to the problem. However, I'd still think the issue would be replicated sometimes even with a single-node deployment, no? Considering that it would affect every node with the default mempool settings, and thus have an impact due to the network effects.

I'll reach out to the Ecko team and update the config used for their nodes with the mempool changes from #1613, to help anyone trying to investigate this issue. Will update here after the config change has gone live.

**Comment by masch1na** [comment]
Hey @wwared , thanks so much for your input. Let us know once the changes are live, eager to test.

However, regardless of the fact that there are load balances nodes - this shouldn't happen. If two different nodes receive a transaction at the same time, there is no reason for the transaction not to be included in the same block, but 2 blocks later with the block inbetween being empty. 

I have some more tests with my own node that I want to perform, will report later when I have time.

**Comment by masch1na** [comment]
Hey wwared, very good info about the fact that those nodes are load balanced. This gave me an idea for another test.

I now did a test sending two transactions at the same time to two different nodes - one to "eu-node-1.hypercent.io", one to "kadena2.app.runonflux.io". 

This time out of 12 tests, 4 times the transactions were mined on different heights. Twice actually with two heights between each other.

This is 1000000% a technical issue worth investigating and spending time on by the team.

**Comment by edmundnoble** [comment]
Thank you for your report.

The config flags mentioned in #1613 may be able to decrease mempool latency, but they do so by increasing the amount of mempool-related network traffic on the P2P network. They decrease the number of hops between nodes by allowing each node to sync to 30 other nodes rather than 6, and they make nodes poll each other for new transactions every 10 seconds rather than every 30 seconds. Telemetry on our own nodes suggests that the mempool accounts for the majority of the traffic on the P2P network, making these measures a somewhat risky proposition.

There have been efforts internal to Kadena to optimize the architecture of the mempool to a number of ends, including decreasing its propagation delay and decreasing the amount of network traffic it produces. However, I'm sorry to say that they haven't been brought to the finish line yet, partly because they are such a big undertaking to do correctly; we need to experiment, monitor, and we may even have to simulate these changes before putting them into production, and frankly the delay has seemed fine for most users, even if it's not as short as it could be.

**Comment by jwiegley** [comment]
> It's not the end of the world the way it is now, but the fact that transactions created at the same time are sometimes mined 2-3 heights apart just isn't right. You are right, the delay might be fine for a casual user who does coin transfer once a month, but there are times when this isn't fine, hence the report. I guess I will have to figure out some workarounds... I have some specific real-life examples that are quite horrific which I am happy to share in private with the devs. Please get in touch on discord masch1na#4142 if interested.

Hi @masch1na, I wanted to respond to the idea that the behavior you've noticed "isn't right":

In a distributed, decentralized system like Kadena, there is no guarantee that:

  1. Two transactions received at the same time will be gossiped to the network at the same time, due to queue lengths and the possibility that one message fits into the queue and the other has to wait until it empties;
  2. Two transactions gossiped at the same time will be re-gossiped by other nodes also at the same time;
  3. These two transactions sitting in the mempool, due to the P2P traffic, will be "right next to each other" in the mempool of the node used by the blockmaker, who may choose to put one into one block, and another into another block, for any of a number of reasons.

The analogy to consider here is a lot more like putting two letters into your mailbox at home, at the same time and both destined for the same address. While it's likely that the postal person will pick them up at the same time, there is no guarantee that they will stay "bundled" throughout the process of sorting, shipping and delivery. It will probably happen often, but is in no way guaranteed. It could be days between their delivery, in fact, due to all sorts of other factors.

Kadena therefore offers no guarantees when it comes to contemporaneous receipt at the node, as to when the transactions are mined, distributed, and evaluated. If you truly need two transfers to happen at the same time on chain, the only definite solution is to post the calls to `coin.transfer` in the same transaction.

**Comment by larskuhtz** [comment]
Here is a typical mempool propagation profile of a pending transaction:
<img width="554" alt="image" src="https://user-images.githubusercontent.com/1369810/227802995-394d6f45-6f90-4cdc-82f3-6aadb82e0b77.png">
The time on the x-axis is in seconds. The y-axis shows the number of mempools/nodes where the tx is present.

### Lifecycle of a Pending Transaction

A typical transaction transitions through the following phases:

1. Tx is submitted to a single mempool where it stays for a while until the next sync with a peer happens.
2. Tx is gossiped between mempools. The number of mempools where the tx is available grows exponentially over time. The curve flattens a bit once the network is almost saturated.
3. When the tx arrives at mining nodes it waits until the currently mined parent block is resolved.
4. When the previous block is resolved the tx gets included into the next block (assuming the block is notcompletely filled with txs of higher priority). It will then be deleted from the mempool of the mining nodes. It remains pending in the mempools of all non-mining nodes.
5. When block with the tx is resolved, the block is propagated (with high priority) throughout the network. When a node validates the respective block the tx is deleted from the mempool of that node.

### Transaction Propagation Histogram

The following chart shows the distribution of how long it takes transactions to be propagated to 90% of all nodes in the network:

<img width="577" alt="image" src="https://user-images.githubusercontent.com/1369810/227809261-ebfe0889-8868-4285-986d-6632f9119f38.png">

Most transactions take less than 50 seconds in order to propagate to almost all nodes in mainnet.

### Remarks

The time that a tx is waiting for the previous block to be mined and the time that the block that includes the tx is mined does not depend on the implementation of the mempool. In particular it has nothing to do with the implementation or parameterization of the P2P network. Typically this makes up at least 50% of the lifetime of a pending transaction.

How fast a tx gets included in a block depends on how long it has to wait for the previous block to be minded after the tx arrives at a mining node. There is a relatively chance that it arrives at some mining node right before mining of a new block starts and at other mining node when mining has already started. Depending on which mining node wins the block, that transaction may be included at the respective block height or may "skip" that block.

Block mining times are distributed exponentially. That distribution as a lot of mass at shorter block times to make up for the long tail. That means many blocks are mined very quickly (within just some seconds). Therefore it can happen regularly that transactions "skip" more than one block when they arrive with just a few seconds of delay at different mining nodes. That, however, doesn't necessarily mean that those transactions have to "wait" longer to be included in "some" block. Because blocks may just be mined more quickly. On the other hand it can take a long until a transaction is included in the next block, if that block (or the previous block) happened to take a long time to be mined. Therefore, just counting block heights (or "skipped" blocks) is not a good a measure of tx latency times.
