### ISSUE TITLE
Nodes that are behind the current block height return outdated states

### ISSUE THREAD

**Issue by ggobugi27** [kadena-io/chainweb-node#493]
I have noticed that making request to `/local` endpoints to the nodes that are behind the current block height return incorrect information from old state. 

For instance, making `(coin.account-balance 'user)` to the node that was down for a while returned the old balance of the user which was not true in the nodes that were ahead.

This behavior results in confusion and can lead to misuses, and there needs to be a decision whether it is to block requests in these nodes or to return certain http status codes, etc.

**Comment by larskuhtz** [comment]
The problem is that nodes don't necessarily know when they are behind. They could be on a fork that they think is legitimate. 

Even if a node is aware that there are nodes in the network that claim to have a larger block height, a node shouldn't trust those until it verified the claim. Otherwise this would be a DOS attack vector.

We may, however, consider adding an explicit mode for catchup during which the pact API is disabled.
