### ISSUE TITLE
What does success look like?

### ISSUE THREAD

**Issue by Fresheyeball** [kadena-io/chainweb-node#648]
I got the cpu miner going.... I think. Since I ran the `chainweb-miner cpu` command with appropriate `--miner-account` `--miner-key` and `--node` arguments, it output the following and nothing else: 

```
2019-11-04 12:23:20.308475: [info] Starting Miner.
```

Does this mean its working? It has output nothing further since I ran the command. If there is an error condition, I feel like the cli should say so. If this is a success condition, I feel like the cli should say so. Saying "Starting" and then nothing is ambiguous.

**Comment by emilypi** [comment]
hey @Fresheyeball - sorry for the late reply. If you log at `--log-level debug`, you can see all of the steps the miner is taking. Since "info" is only going to log at info and error, you'll only see failures and successfully mined blog messages. For example, here are some samples of what you'll get from each log-level:

Info (shown at loglevel info):
```
2019-11-24 12:00:02.243755: [info] Chain 9: Mined block at Height 74799. (4s since last)
```

Error (shown at loglevel info):
```
2019-11-24 17:12:53.160939: [error] No nodes left!
```

Warn (shown at log level warn):
```
2019-11-24 17:12:53.160603: [warn] HTTP Request failed with code 403: Forbidden
```

Debug (shown only at loglevel debug):
```
2019-11-24 12:00:02.697844: [debug] Attempting to fetch new work from the remote Node
2019-11-24 12:00:03.285160: [debug] Chain 4: Start mining on new work item.
```

>Saying "Starting" and then nothing is ambiguous.

We offer a whole bunch of solutions to this by setting the loglevel and filters for what messages you care about seeing. Hopefully this answers your question.
