### ISSUE TITLE
Couldn't connect to update stream

### ISSUE THREAD

**Issue by cryptosword6319** [kadena-io/chainweb-node#659]
Allways getting "[warn] Couldn't connect to update stream. Trying again" with chainweb-miner
What does this mean? How to fix it?

**Comment by emilypi** [comment]
Hey @cryptosword6319 - sorry about the late reply on this. That was the message a node would give when it couldn't connect to another node's updates during the gossip phase. The causes for this would be that a particular node was unreachable because it was down, had too many requests in its queue, or was unreachable at the network level. The code that features that warning has since been refactored and gossiping is much more informative.
