### ISSUE TITLE
Review nonce bytes

### ISSUE THREAD

**Issue by tianchaijz** [kadena-io/chainweb-node#862]
Now nonce is 8 bytes length, if Kadena will be a successful project, we will see ASIC in less 1 year, current ASIC performance over GPU and FPGA is dramatic, so it probably wise to use 32 bytes nonce. Usually pools will lease at least 3 bytes (2 bytes is not enough for allocation) for extra nonce. So only 5 bytes left for miner which could be not enough, `blake2s` ASIC with `1T` hashrate can run out the nonces in less than 1 second and the chain block time is 30s now.

Relevant issue: https://github.com/kadena-io/chainweb-node/issues/297

PS: Kadena stratum protocol: https://gist.github.com/tianchaijz/1abef4ce196212e8aabef0c343a86240

**Comment by mightybyte** [comment]
We discussed the nonce size issue during development because the same concern had been raised.  The consensus was that there are enough other bytes available to be varied that this shouldn't be a problem.  As mentioned in #297, miners can also control the block creation time as well as the miner address.  The miner address includes the account name (up to 256 bytes, see https://github.com/kadena-io/chainweb-node/blob/master/pact/coin-contract/coin.pact#L16) and public key.  My recommendation would be to not lease any of the nonce bytes and use these other sources of variation.  It seems to me that this should be enough.  What do you think?

**Comment by tianchaijz** [comment]
@mightybyte thanks for your reply. Assign each miner a unique mining address on the pool side is unpractical, the timestamp could be stretched a bit, but moving it too far into the future would cause the block to become invalid? Since BTC can use the coinbase transaction as a source of extra nonce values and i see a `payload` field in the header of KDA, can use this field as a source of extra nonce?

**Comment by tianchaijz** [comment]
We can use `flags` field as extra nonce.
